import fs from "node:fs/promises";
import path from "node:path";
import type { ResolvedToolchain, ToolchainConfig, ToolchainLock } from "./types.js";
import { isLatestVersion } from "./pinning.js";
import { runShell } from "../utils/process.js";
import { currentOperationContext } from "../operations/state.js";
import { persistCommandDiagnosticV1 } from "../operations/forensics.js";

export interface MiseAdapter {
  command: string;
  version?: string;
}

export async function resolveMiseAdapter(root: string, minimumVersion?: string): Promise<MiseAdapter> {
  const bootstrap = minimumVersion
    ? `npm exec --yes --package=mise@${shellBare(minimumVersion)} -- mise`
    : "npm exec --yes --package=mise -- mise";
  const candidates = ["mise", bootstrap];
  const diagnostics: string[] = [];
  for (const command of candidates) {
    const fullCommand = `${command} --version`;
    const startedAt = new Date().toISOString();
    const result = await runShell(fullCommand, { cwd: root, timeoutMs: 60_000, toolchain: false, captureOutputLimitBytes: 128 * 1024 });
    if (result.exitCode !== 0) {
      const failure = await safeToolchainCommandFailure(root, fullCommand, "mise", undefined, result, startedAt);
      const diagnostic = failure.message.match(/diagnostic=(.*)\.$/)?.[1];
      if (diagnostic && diagnostic !== "unavailable") diagnostics.push(diagnostic);
      continue;
    }
    const version = parseVersion(result.stdout || result.stderr);
    if (minimumVersion && version && compareVersions(version, minimumVersion) < 0) continue;
    return { command, version };
  }
  throw new Error(`mise ${minimumVersion ? `>= ${minimumVersion} ` : ""}is required for toolchain setup. AEH attempted the configured/pinned npm bootstrap; install mise explicitly if that bootstrap is unavailable.${diagnostics.length ? ` Diagnostics: ${diagnostics.join(", ")}.` : ""}`);
}

export async function writeMiseConfig(
  root: string,
  file: string,
  toolchain: ToolchainConfig,
  resolved: ResolvedToolchain,
  lock: ToolchainLock | undefined,
  updateLock: boolean
): Promise<void> {
  const lines = ["# Generated by Agentic Engineering Harness. Edit .harness/toolchain.yaml instead.", "", "[settings]", "lockfile = true", ""];
  lines.push("[tools]");
  for (const tool of resolved.tools.filter((item) => item.provisioning === "mise")) {
    const version = !updateLock ? lock?.tools[tool.name]?.resolvedVersion ?? tool.version : tool.version;
    if (isLatestVersion(version)) {
      throw new Error(`TOOLCHAIN_UNPINNED_VERSION: toolchain tool '${tool.name}' has no pinned version (got '${version ?? "<missing>"}'). Pin an exact version in .harness/toolchain.yaml.`);
    }
    lines.push(`${tomlKey(tool.source!)} = ${JSON.stringify(version)}`);
  }
  lines.push("");
  const target = path.resolve(root, file); await fs.mkdir(path.dirname(target), { recursive: true }); await fs.writeFile(target, `${lines.join("\n")}\n`);
}

export async function installMiseTools(root: string, adapter: MiseAdapter, tools: string[], dryRun = false, updateLock = false): Promise<void> {
  const trustCommand = `${adapter.command} trust`;
  const trustStartedAt = new Date().toISOString();
  const trust = await runShell(trustCommand, { cwd: root, timeoutMs: 30_000, toolchain: false, captureOutputLimitBytes: 128 * 1024 });
  if (trust.exitCode !== 0 && !/already trusted/i.test(`${trust.stdout}\n${trust.stderr}`)) throw await safeToolchainCommandFailure(root, trustCommand, "mise", adapter.version, trust, trustStartedAt);
  if (updateLock) {
    const targets = tools.map(shell).join(" ");
    // Python CLI transitive graphs are wheel-only in mise.lock; keep pipx on
    // version-only locking so source-only dependencies can use normal installs.
    const command = `${adapter.command} lock --bump ${targets}`;
    const startedAt = new Date().toISOString();
    const bump = await runShell(command, {
      cwd: root,
      timeoutMs: 1_800_000,
      env: { MISE_PIPX_UVX: "false", MISE_PYPI_UVX: "false" },
      toolchain: false,
      captureOutputLimitBytes: 128 * 1024
    });
    if (bump.exitCode !== 0) throw await safeToolchainCommandFailure(root, command, "mise", adapter.version, bump, startedAt, { MISE_PIPX_UVX: "false", MISE_PYPI_UVX: "false" });
  }
  const command = `${adapter.command} -y install${dryRun ? " --dry-run" : ""}`;
  const startedAt = new Date().toISOString();
  const result = await runShell(command, { cwd: root, timeoutMs: 1_800_000, toolchain: false, captureOutputLimitBytes: 128 * 1024 });
  if (result.exitCode !== 0) throw await safeToolchainCommandFailure(root, command, "mise", adapter.version, result, startedAt);
}

export async function miseResolvedVersion(root: string, adapter: MiseAdapter, command: string): Promise<string | undefined> {
  const result = await runShell(`${adapter.command} which ${shell(command)} --version`, { cwd: root, timeoutMs: 30_000, toolchain: false });
  return result.exitCode === 0 ? result.stdout.trim() || undefined : undefined;
}

export async function miseBinPaths(root: string, adapter: MiseAdapter): Promise<string[]> {
  const command = `${adapter.command} bin-paths`;
  const startedAt = new Date().toISOString();
  const result = await runShell(command, { cwd: root, timeoutMs: 30_000, toolchain: false, captureOutputLimitBytes: 128 * 1024 });
  if (result.exitCode !== 0) throw await safeToolchainCommandFailure(root, command, "mise", adapter.version, result, startedAt);
  return [...new Set(result.stdout.split(/\r?\n/).map((value) => value.trim()).filter(Boolean))];
}

async function safeToolchainCommandFailure(root: string, command: string, toolName: string, toolVersion: string | undefined, result: Awaited<ReturnType<typeof runShell>>, startedAt: string, environment?: Record<string, string | undefined>): Promise<Error> {
  const diagnostic = await persistCommandDiagnosticV1({
    root,
    operationId: currentOperationContext().id,
    command,
    cwd: root,
    result,
    toolName,
    toolVersion,
    ...(environment ? { environment } : {}),
    startedAt
  }).catch(() => undefined);
  return new Error(`Toolchain command failed (exitCode=${result.exitCode}); diagnostic=${diagnostic ?? "unavailable"}.`);
}

function tomlKey(value: string): string { return /^[A-Za-z0-9_-]+$/.test(value) ? value : JSON.stringify(value); }
function shell(value: string): string { return `'${value.replaceAll("'", "'\\''")}'`; }
function shellBare(value: string): string { if (!/^[A-Za-z0-9._-]+$/.test(value)) throw new Error(`Unsafe mise bootstrap version: ${value}`); return value; }
function parseVersion(value: string): string | undefined { return value.match(/(\d{4}\.\d+(?:\.\d+)?|\d+\.\d+(?:\.\d+)?)/)?.[1]; }
function compareVersions(left: string, right: string): number { const a = left.split(".").map(Number), b = right.split(".").map(Number); for (let i = 0; i < Math.max(a.length, b.length); i++) { const diff = (a[i] ?? 0) - (b[i] ?? 0); if (diff) return diff; } return 0; }
