import fs from "node:fs/promises";
import path from "node:path";
import type { ResolvedToolchain, ToolchainConfig, ToolchainLock } from "./types.js";
import { runProcess } from "../utils/process.js";

export interface MiseAdapter {
  command: string;
  version?: string;
}

export async function resolveMiseAdapter(root: string, minimumVersion?: string): Promise<MiseAdapter> {
  const candidates = ["mise", "npm exec --yes -- mise"];
  for (const command of candidates) {
    const result = await runProcess(`${command} --version`, { cwd: root, timeoutMs: 30_000, toolchain: false });
    if (result.exitCode !== 0) continue;
    const version = parseVersion(result.stdout || result.stderr);
    if (minimumVersion && version && compareVersions(version, minimumVersion) < 0) continue;
    return { command, version };
  }
  throw new Error(`mise ${minimumVersion ? `>= ${minimumVersion} ` : ""}is required for toolchain setup. Installing AEH through npm includes mise; alternatively install mise from https://mise.run.`);
}

export async function writeMiseConfig(
  root: string,
  file: string,
  toolchain: ToolchainConfig,
  resolved: ResolvedToolchain,
  lock: ToolchainLock | undefined,
  updateLock: boolean
): Promise<void> {
  const lines = ["# Generated by Agentic Engineering Harness. Edit .harness/toolchain.yaml instead.", "", "[settings]", "lockfile = true", ""];
  lines.push("[tools]");
  for (const tool of resolved.tools.filter((item) => item.provisioning === "mise")) {
    const version = !updateLock ? lock?.tools[tool.name]?.resolvedVersion ?? tool.version ?? "latest" : tool.version ?? "latest";
    lines.push(`${tomlKey(tool.source!)} = ${JSON.stringify(version)}`);
  }
  lines.push("");
  const target = path.resolve(root, file); await fs.mkdir(path.dirname(target), { recursive: true }); await fs.writeFile(target, `${lines.join("\n")}\n`);
}

export async function installMiseTools(root: string, adapter: MiseAdapter, dryRun = false): Promise<void> {
  const trust = await runProcess(`${adapter.command} trust`, { cwd: root, timeoutMs: 30_000, toolchain: false });
  if (trust.exitCode !== 0 && !/already trusted/i.test(`${trust.stdout}\n${trust.stderr}`)) throw new Error(`mise trust failed: ${trust.stderr || trust.stdout}`);
  const command = `${adapter.command} -y install${dryRun ? " --dry-run" : ""}`;
  const result = await runProcess(command, { cwd: root, timeoutMs: 1_800_000, toolchain: false });
  if (result.exitCode !== 0) throw new Error(`mise install failed: ${result.stderr || result.stdout}`);
}

export async function miseResolvedVersion(root: string, adapter: MiseAdapter, command: string): Promise<string | undefined> {
  const result = await runProcess(`${adapter.command} which ${shell(command)} --version`, { cwd: root, timeoutMs: 30_000, toolchain: false });
  return result.exitCode === 0 ? result.stdout.trim() || undefined : undefined;
}

export async function miseBinPaths(root: string, adapter: MiseAdapter): Promise<string[]> {
  const result = await runProcess(`${adapter.command} bin-paths`, { cwd: root, timeoutMs: 30_000, toolchain: false });
  if (result.exitCode !== 0) throw new Error(`mise bin-paths failed: ${result.stderr || result.stdout}`);
  return [...new Set(result.stdout.split(/\r?\n/).map((value) => value.trim()).filter(Boolean))];
}

function tomlKey(value: string): string { return /^[A-Za-z0-9_-]+$/.test(value) ? value : JSON.stringify(value); }
function shell(value: string): string { return `'${value.replaceAll("'", "'\\''")}'`; }
function parseVersion(value: string): string | undefined { return value.match(/(\d{4}\.\d+(?:\.\d+)?|\d+\.\d+(?:\.\d+)?)/)?.[1]; }
function compareVersions(left: string, right: string): number { const a = left.split(".").map(Number), b = right.split(".").map(Number); for (let i = 0; i < Math.max(a.length, b.length); i++) { const diff = (a[i] ?? 0) - (b[i] ?? 0); if (diff) return diff; } return 0; }
