import path from "node:path";
import type { AgentExecutionSelection } from "../agents/types.js";
import type { HarnessProjectConfig, RepairPacket, TaskContract, WorkerSession } from "../core/types.js";
import { commandExists, runProcess } from "../utils/process.js";
import { buildRepairPrompt, buildWorkerPrompt } from "./prompt.js";
import type { WorkerExecutor } from "./types.js";
export class PodmanWorkerExecutor implements WorkerExecutor { readonly name = "podman";
  async doctor(root: string, config: HarnessProjectConfig): Promise<{ ok: boolean; message: string }> { const ok = await commandExists("podman", root); if (!ok) return { ok: false, message: "Podman CLI not found." }; if (!config.security?.sandbox?.image) return { ok: false, message: "security.sandbox.image is required for Podman worker execution." }; return { ok: true, message: "Podman worker sandbox configured." }; }
  async start(root: string, config: HarnessProjectConfig, contract: TaskContract, selection?: AgentExecutionSelection): Promise<WorkerSession> { return this.run(root, config, contract, buildWorkerPrompt(contract, selection), selection); }
  async repair(root: string, config: HarnessProjectConfig, contract: TaskContract, _session: WorkerSession, packet: RepairPacket, selection?: AgentExecutionSelection): Promise<WorkerSession> { return this.run(root, config, contract, `${buildWorkerPrompt(contract, selection)}\n\n${buildRepairPrompt(packet)}`, selection); }
  private async run(root: string, config: HarnessProjectConfig, contract: TaskContract, prompt: string, selection?: AgentExecutionSelection): Promise<WorkerSession> { const sandbox = config.security?.sandbox; const image = sandbox?.image; if (!image) throw new Error("Podman image is not configured."); const runtime = selection?.runtimeAdapter ?? "opencode"; if (runtime !== "opencode") throw new Error(`Podman executor currently supports OpenCode runtime; selected ${runtime}.`); const model = selection?.modelId ?? config.orchestration?.worker?.model; const mounts = [`-v ${quote(`${root}:/workspace:rw`)}`]; for (const relative of sealedArtifacts(config, contract)) mounts.push(`-v ${quote(`${path.resolve(root, relative)}:/workspace/${relative}:ro`)}`); const network = sandbox?.network === false ? "--network none" : ""; const extra = (sandbox?.extraArgs ?? []).map(quote).join(" "); const args = ["opencode", "run", "--auto"]; if (model) args.push("--model", model); if (selection?.variant) args.push("--variant", selection.variant); if (selection?.nativeAgent) args.push("--agent", selection.nativeAgent); args.push(...(selection?.args ?? []), prompt); const inner = `cd /workspace && ${args.map(quote).join(" ")}`; const command = `podman run --rm -i --userns=keep-id ${network} ${extra} ${mounts.join(" ")} ${quote(image)} sh -lc ${quote(inner)}`; const timeout = config.orchestration?.worker?.timeoutSeconds ?? 1800; const result = await runProcess(command, { cwd: root, timeoutMs: timeout * 1000 }); return { provider: runtime, model: selection?.modelName ?? model, logicalAgent: selection?.logicalAgent, nativeAgent: selection?.nativeAgent, runtime: selection?.runtimeName, profile: selection?.profile, exitCode: result.exitCode, stdout: result.stdout, stderr: result.stderr }; }
}
function sealedArtifacts(config: HarnessProjectConfig, contract: TaskContract): string[] { const contractsDir = config.sdd?.contractsDir ?? ".harness/contracts"; return [...new Set([`${contractsDir}/${contract.task.id}.yaml`, `.harness/seals/${contract.task.id}.json`, ...Object.values(contract.source ?? {}).filter((value): value is string => Boolean(value))])]; }
function quote(value: string): string { return `'${value.replaceAll("'", "'\\''")}'`; }
