import fs from "node:fs/promises";
import path from "node:path";
import type { AgentExecutionSelection, ResolvedAgentTopology, ResolvedRoute } from "../agents/types.js";
import { auditAgentTopology } from "../agents/audit.js";
import { loadResolvedAgentTopology } from "../agents/config.js";
import { classifyFailure, formatRecoveryAction, resolveRecoveryStep } from "../agents/recovery.js";
import { executionSelectionForAgent, selectExecutionForTask, selectFallbackExecution } from "../agents/routing.js";
import { validateExecutionCapabilities } from "../agents/permissions.js";
import type { HarnessProjectConfig, RunMetrics, TaskContract, ValidationReport, WorkerSession } from "./types.js";
import { validateSddChange } from "./sdd.js";
import { sealTask } from "./seal.js";
import { verifyTask } from "./verify.js";
import { createRepairPacket, writeRepairPacket } from "./repair.js";
import { createWorkerExecutor } from "../workers/factory.js";
import { snapshotGraph } from "../validators/graphify.js";
import { runProcess } from "../utils/process.js";
import { recordEvent } from "../telemetry/events.js";
import { extractUsageMetrics } from "../metrics/usage.js";
import { buildRunMetrics, countHumanInterventions } from "../metrics/runMetrics.js";
export interface TaskRunResult { taskId: string; status: "PASS" | "FAIL"; attempts: number; worker: WorkerSession; report: ValidationReport; metrics: RunMetrics; routing?: { profile?: string; ruleIds: string[]; agent: string; runtime: string; model: string; nativeAgent?: string; reviewers: string[]; validators: string[]; }; }
export async function runTask(root: string, config: HarnessProjectConfig, contract: TaskContract, options?: { profile?: string }): Promise<TaskRunResult> {
  const startedMs = Date.now(); const startedAt = new Date(startedMs).toISOString(); const trace = await validateSddChange(root, contract.task.id, config); if (!trace.ok) throw new Error(`SDD validation failed before delegation:\n${[...trace.missing, ...trace.issues].map((item) => `- ${item}`).join("\n")}`); await recordEvent(root, config, "harness.run.start", { taskId: contract.task.id }); await sealTask(root, config, contract);
  const topologyState = await resolveTopology(root, config, contract, options?.profile); const topology = topologyState.topology; const route = topologyState.route; let selection = topologyState.selection;
  await refreshGraphIfConfigured(root, config); const beforeSnapshot = await snapshotGraph(root, config, contract.task.id, "before"); if (!beforeSnapshot && config.codeIntelligence?.required) throw new Error("Code intelligence is required but the Graphify before snapshot could not be created.");
  let executor = createWorkerExecutor(config, selection); const health = await executor.doctor(root, config, selection); if (!health.ok) throw new Error(`${executor.name} executor unavailable: ${health.message}`); let worker = await executor.start(root, config, contract, selection); let attempts = 0; let report = withWorkerExecutionCheck(await verifyAfterWorker(root, config, contract), worker); const firstPassSuccess = report.status === "PASS"; const maxRepairs = contract.repair?.maxAttempts ?? config.orchestration?.worker?.maxRepairAttempts ?? 2;
  while (report.status === "FAIL" && attempts < maxRepairs) {
    attempts += 1; const failureType = classifyFailure({ report, worker }); const recovery = topology ? resolveRecoveryStep(topology, failureType, attempts) : { action: "same-agent" as const }; const recoveryAction = formatRecoveryAction(recovery, selection?.logicalAgent ?? "legacy-worker"); const packet = createRepairPacket(report, attempts, { failureType, failedAgent: selection?.logicalAgent, recoveryAction }); if (!packet.failures.length) break; await writeRepairPacket(root, config, packet); await recordEvent(root, config, "harness.repair.start", { taskId: contract.task.id, attempt: attempts, failureType, recoveryAction, failures: packet.failures.length });
    if (recovery.action === "lead" || recovery.action === "stop") break; if (topology && recovery.action === "agent" && recovery.agent) selection = executionSelectionForAgent(topology, recovery.agent); else if (topology && recovery.action === "reroute") { const fallback = selectFallbackExecution(topology, contract, selection?.logicalAgent ?? ""); if (!fallback) break; selection = fallback; }
    if (selection) { const transport = selection.transport === "inherit" ? (config.orchestration?.provider ?? "none") : selection.transport; const issues = validateExecutionCapabilities(selection, transport); if (issues.length) throw new Error(`Recovery agent ${selection.logicalAgent} is not executable: ${issues.join("; ")}`); }
    executor = createWorkerExecutor(config, selection); const recoveryHealth = await executor.doctor(root, config, selection); if (!recoveryHealth.ok) throw new Error(`${executor.name} recovery executor unavailable: ${recoveryHealth.message}`); worker = await executor.repair(root, config, contract, worker, packet, selection); report = withWorkerExecutionCheck(await verifyAfterWorker(root, config, contract), worker); await recordEvent(root, config, "harness.repair.finish", { taskId: contract.task.id, attempt: attempts, status: report.status, agent: selection?.logicalAgent });
  }
  worker.metrics = extractUsageMetrics(`${worker.stdout}\n${worker.stderr}`); const metrics = buildRunMetrics({ firstPassSuccess, repairCount: attempts, humanInterventions: await countHumanInterventions(root, config, contract.task.id, startedAt), durationMs: Date.now() - startedMs, usage: worker.metrics }); const routing = selection ? { profile: selection.profile, ruleIds: route?.ruleIds ?? [], agent: selection.logicalAgent, runtime: selection.runtimeName, model: selection.modelId, nativeAgent: selection.nativeAgent, reviewers: route?.reviewers ?? [], validators: route?.validators ?? [] } : undefined; const result: TaskRunResult = { taskId: contract.task.id, status: report.status, attempts, worker, report, metrics, routing }; const runsDir = path.resolve(root, config.sdd?.runsDir ?? ".harness/runs"); await fs.mkdir(runsDir, { recursive: true }); await fs.writeFile(path.join(runsDir, `${contract.task.id}.json`), `${JSON.stringify(result, null, 2)}\n`); await recordEvent(root, config, "harness.run.finish", { taskId: contract.task.id, status: result.status, attempts, agent: selection?.logicalAgent, runtime: selection?.runtimeName, model: selection?.modelId, profile: selection?.profile, durationMs: metrics.durationMs, totalTokens: metrics.usage.totalTokens ?? 0, costUsd: metrics.usage.costUsd ?? 0 }); return result;
}
async function resolveTopology(root: string, config: HarnessProjectConfig, contract: TaskContract, profileOverride?: string): Promise<{ topology?: ResolvedAgentTopology; route?: ResolvedRoute; selection?: AgentExecutionSelection }> { if (!config.agents) return {}; const explicitProfile = profileOverride ?? contract.routing?.profile; const profile = explicitProfile ?? config.agents.activeProfile; try { const audit = await auditAgentTopology(root, config, profile, { checkGenerated: !explicitProfile }); if (!audit.ok) throw new Error(`Agent topology audit failed:\n${audit.checks.filter((check) => check.status === "FAIL").map((check) => `- ${check.id}: ${check.message}`).join("\n")}`); const topology = await loadResolvedAgentTopology(root, config, profile); const { route, selection } = selectExecutionForTask(topology, contract); const transport = selection.transport === "inherit" ? (config.orchestration?.provider ?? "none") : selection.transport; const issues = validateExecutionCapabilities(selection, transport); if (issues.length) throw new Error(`Selected agent ${selection.logicalAgent} is not executable: ${issues.join("; ")}`); await recordEvent(root, config, "harness.agent.route", { taskId: contract.task.id, profile, agent: selection.logicalAgent, runtime: selection.runtimeName, model: selection.modelId, nativeAgent: selection.nativeAgent, transport, ruleIds: route.ruleIds, reviewers: route.reviewers }); return { topology, route, selection }; } catch (error) { if (config.agents.required) throw error; await recordEvent(root, config, "harness.agent.topology-fallback", { taskId: contract.task.id, error: String(error) }); return {}; } }
function withWorkerExecutionCheck(report: ValidationReport, worker: WorkerSession): ValidationReport { const checks = report.checks.filter((check) => check.id !== "agent.execution"); checks.unshift({ id: "agent.execution", category: "agent-runtime", status: worker.exitCode === 0 ? "PASS" : "FAIL", message: worker.exitCode === 0 ? `Agent ${worker.logicalAgent ?? worker.provider} completed successfully.` : `Agent runtime exited with code ${worker.exitCode}.`, details: worker.exitCode === 0 ? undefined : { stderr: worker.stderr.slice(-4000), stdout: worker.stdout.slice(-4000), logicalAgent: worker.logicalAgent, runtime: worker.runtime, model: worker.model } }); return { ...report, checks, status: checks.some((check) => check.status === "FAIL") ? "FAIL" : "PASS" }; }
async function verifyAfterWorker(root: string, config: HarnessProjectConfig, contract: TaskContract): Promise<ValidationReport> { await refreshGraphIfConfigured(root, config); const afterSnapshot = await snapshotGraph(root, config, contract.task.id, "after"); if (!afterSnapshot && config.codeIntelligence?.required) throw new Error("Code intelligence is required but the Graphify after snapshot could not be created."); return verifyTask(root, config, contract); }
async function refreshGraphIfConfigured(root: string, config: HarnessProjectConfig): Promise<void> { const command = config.codeIntelligence?.refreshCommand; if (!command) return; const result = await runProcess(command, { cwd: root, timeoutMs: 300_000 }); if (result.exitCode !== 0 && config.codeIntelligence?.required) throw new Error(`Code intelligence refresh failed: ${result.stderr || result.stdout}`); }
