import fs from "node:fs/promises";
import path from "node:path";
import type { AgentExecutionSelection, ResolvedAgentTopology, ResolvedRoute } from "./types.js";
import { executionSelectionForAgent } from "./routing.js";
import { validateExecutionCapabilities } from "./permissions.js";
import { dedupeFindings, type DedupedFindings } from "./findings.js";
import { orchestratorOutputSchema, reviewerOutputSchema, type NormalizedFinding } from "./outputContracts.js";
import { extractMarkedJson } from "./structuredOutput.js";
import type { HarnessProjectConfig, TaskContract, ValidationCheck, ValidationReport, WorkerSession } from "../core/types.js";
import { executeAgentPrompt } from "../workers/agentPrompt.js";
import { recordEvent } from "../telemetry/events.js";

export interface ReviewLifecycleResult { status: "PASS" | "FAIL"; rounds: number; report: ValidationReport; findings: DedupedFindings; checks: ValidationCheck[]; sessions: WorkerSession[]; leadAccepted?: boolean; }
export async function runReviewLifecycle(input: { root: string; config: HarnessProjectConfig; contract: TaskContract; topology: ResolvedAgentTopology; route: ResolvedRoute; implementationSelection: AgentExecutionSelection; report: ValidationReport; revalidate: () => Promise<ValidationReport>; }): Promise<ReviewLifecycleResult> {
  const { root, config, contract, topology, route, implementationSelection } = input; let report = input.report; const sessions: WorkerSession[] = []; const checks: ValidationCheck[] = [];
  const policy = config.workflow?.reviews; if (policy?.enabled === false) return emptyResult(report, checks, sessions);
  const isQuick = contract.mode === "quick"; const runReviewers = !isQuick || policy?.reviewQuick === true; const reviewerNames = runReviewers ? route.reviewers : [];
  const blocking = new Set(policy?.blockingSeverities ?? ["critical", "high", "medium"]); const maxRounds = policy?.maxRemediationRounds ?? 1; let rounds = 0; let deduped: DedupedFindings = { inputCount: 0, outputCount: 0, findings: [], merges: [] };
  while (reviewerNames.length) {
    const findings: NormalizedFinding[] = [];
    const outputs = await Promise.all(reviewerNames.map(async (name) => runReviewer(root, config, contract, topology, name, report)));
    for (const output of outputs) { sessions.push(output.session); findings.push(...output.findings); }
    deduped = dedupeFindings(findings); await persistFindings(root, config, contract.task.id, rounds, deduped); const blockers = deduped.findings.filter((finding) => blocking.has(finding.severity));
    await recordEvent(root, config, "harness.review.round", { taskId: contract.task.id, round: rounds, reviewers: reviewerNames, findings: deduped.outputCount, blockers: blockers.length });
    if (!blockers.length) { checks.push({ id: "agent.reviews", category: "agent-review", status: "PASS", message: `${reviewerNames.length} reviewer(s) accepted the implementation with no blocking findings.`, details: { findings: deduped.findings } }); break; }
    if (rounds >= maxRounds) { checks.push({ id: "agent.reviews", category: "agent-review", status: "FAIL", message: `${blockers.length} blocking reviewer finding(s) remain after ${rounds} remediation round(s).`, details: { findings: blockers } }); return { status: "FAIL", rounds, report, findings: deduped, checks, sessions }; }
    rounds += 1; const remediationSelection = selectRemediator(topology, implementationSelection, blockers); const transport = remediationSelection.transport === "inherit" ? (config.orchestration?.provider ?? "none") : remediationSelection.transport; const capabilityIssues = validateExecutionCapabilities(remediationSelection, transport); if (capabilityIssues.length) throw new Error(`Remediation agent ${remediationSelection.logicalAgent} is not executable: ${capabilityIssues.join("; ")}`);
    const remediation = await executeAgentPrompt(root, config, contract, remediationSelection, buildRemediationPrompt(contract, blockers)); sessions.push(remediation); if (remediation.exitCode !== 0) { checks.push({ id: "agent.remediation", category: "agent-review", status: "FAIL", message: `Remediation agent ${remediationSelection.logicalAgent} failed with exit code ${remediation.exitCode}.` }); return { status: "FAIL", rounds, report, findings: deduped, checks, sessions }; }
    report = await input.revalidate(); if (report.status === "FAIL") { checks.push({ id: "agent.remediation-validation", category: "agent-review", status: "FAIL", message: "Deterministic validation failed after reviewer remediation." }); return { status: "FAIL", rounds, report, findings: deduped, checks, sessions }; }
  }
  const shouldLeadAccept = policy?.leadAcceptance !== false && (!isQuick || policy?.leadAcceptanceQuick === true); let leadAccepted: boolean | undefined;
  if (shouldLeadAccept) { const lead = Object.values(topology.agents).find((agent) => agent.role === "orchestrator" && !agent.disabled); if (!lead) { checks.push({ id: "agent.lead-acceptance", category: "agent-review", status: "FAIL", message: "Lead acceptance is enabled but no orchestrator agent is available." }); return { status: "FAIL", rounds, report, findings: deduped, checks, sessions, leadAccepted: false }; }
    const selection = executionSelectionForAgent(topology, lead.name); const leadSession = await executeAgentPrompt(root, config, contract, selection, buildLeadPrompt(contract, report, deduped)); sessions.push(leadSession); try { const parsed = orchestratorOutputSchema.parse(extractMarkedJson(leadSession.stdout, leadSession.stderr)); leadAccepted = leadSession.exitCode === 0 && parsed.finalizationSafe === true && parsed.unresolved.length === 0; checks.push({ id: "agent.lead-acceptance", category: "agent-review", status: leadAccepted ? "PASS" : "FAIL", message: leadAccepted ? `Lead ${lead.name} accepted finalization.` : `Lead ${lead.name} did not declare finalization safe.`, details: { unresolved: parsed.unresolved, summary: parsed.summary } }); } catch (error) { leadAccepted = false; checks.push({ id: "agent.lead-acceptance", category: "agent-review", status: "FAIL", message: `Lead output contract was invalid: ${String(error)}` }); }
  }
  const status = checks.some((check) => check.status === "FAIL") ? "FAIL" : "PASS"; return { status, rounds, report, findings: deduped, checks, sessions, leadAccepted };
}

async function runReviewer(root: string, config: HarnessProjectConfig, contract: TaskContract, topology: ResolvedAgentTopology, name: string, report: ValidationReport): Promise<{ session: WorkerSession; findings: NormalizedFinding[] }> {
  const selection = executionSelectionForAgent(topology, name); const session = await executeAgentPrompt(root, config, contract, selection, buildReviewerPrompt(contract, name, report)); if (session.exitCode !== 0) return { session, findings: [syntheticFinding(name, `Reviewer runtime exited with code ${session.exitCode}.`)] };
  try { const output = reviewerOutputSchema.parse(extractMarkedJson(session.stdout, session.stderr)); if (output.verdict === "FAIL" && output.findings.length === 0) return { session, findings: [syntheticFinding(name, "Reviewer returned FAIL without a structured finding.")] }; return { session, findings: output.findings }; } catch (error) { return { session, findings: [syntheticFinding(name, `Invalid reviewer output contract: ${String(error)}`)] }; }
}
function selectRemediator(topology: ResolvedAgentTopology, fallback: AgentExecutionSelection, findings: NormalizedFinding[]): AgentExecutionSelection { const names = [...new Set(findings.map((finding) => finding.suggestedAgent))]; if (names.length === 1) { const agent = topology.agents[names[0]]; if (agent && !agent.disabled && agent.permissions?.write === "allow") return executionSelectionForAgent(topology, names[0]); } return fallback; }
export function isBlockingFinding(finding: NormalizedFinding, severities: NormalizedFinding["severity"][] = ["critical", "high", "medium"]): boolean { return severities.includes(finding.severity); }
function syntheticFinding(agent: string, evidence: string): NormalizedFinding { return { id: `REVIEW-${agent}-${Date.now()}`, severity: "critical", category: "review-contract", location: { file: "<review-output>" }, evidence, impact: "The review cannot be trusted as valid evidence.", recommendedFix: "Rerun or repair the reviewer output contract.", suggestedAgent: agent }; }
async function persistFindings(root: string, config: HarnessProjectConfig, taskId: string, round: number, findings: DedupedFindings): Promise<void> { const dir = path.resolve(root, config.agents?.findingsDir ?? ".harness/findings"); await fs.mkdir(dir, { recursive: true }); await fs.writeFile(path.join(dir, `${taskId}-round-${round}.json`), `${JSON.stringify(findings, null, 2)}\n`); }
function buildReviewerPrompt(contract: TaskContract, reviewer: string, report: ValidationReport): string { return `You are reviewer ${reviewer} for ${contract.task.id}. Inspect the actual git diff from ${contract.git?.baseRef ?? "main"}, relevant source/tests, and the sealed task contract. Do not modify files. Deterministic validation currently reports ${report.status}. Return a reviewer output matching: {"verdict":"PASS|FAIL|PASS_WITH_WARNINGS","findings":[{"id":"...","severity":"critical|high|medium|low|note","category":"...","location":{"file":"...","startLine":1,"endLine":1},"evidence":"...","impact":"...","recommendedFix":"...","suggestedAgent":"..."}],"finalizationSafety":"SAFE|BLOCKED|RISK_KNOWN","followUp":[]}. Your final output MUST contain exactly one line beginning AEH_RESULT_JSON= followed by the JSON object.`; }
function buildRemediationPrompt(contract: TaskContract, findings: NormalizedFinding[]): string { return `Remediate blocking review findings for ${contract.task.id}. Do not change sealed contracts/specs/acceptance. Make the smallest changes needed, preserve scope, and run focused checks. Findings:\n${JSON.stringify(findings, null, 2)}\nReport normally when complete.`; }
function buildLeadPrompt(contract: TaskContract, report: ValidationReport, findings: DedupedFindings): string { return `You are the lead engineer performing final semantic acceptance for ${contract.task.id}. Inspect the actual final diff, sealed requirements/QuickContract, deterministic report and reviewer evidence. Do not modify files. Deterministic status=${report.status}. Remaining normalized findings=${JSON.stringify(findings.findings)}. Return {"summary":"...","delegatedAgents":[],"validationStatus":"${report.status}","unresolved":[],"finalizationSafe":true|false}. Your final output MUST contain exactly one line beginning AEH_RESULT_JSON= followed by the JSON object.`; }
function emptyResult(report: ValidationReport, checks: ValidationCheck[], sessions: WorkerSession[]): ReviewLifecycleResult { return { status: "PASS", rounds: 0, report, findings: { inputCount: 0, outputCount: 0, findings: [], merges: [] }, checks, sessions }; }
